import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author melik
 */
public class Zikirmatik extends javax.swing.JFrame {

    Icon arti_Siyah = new ImageIcon(getClass().getResource("/Ýconlar/Ekran görüntüsü 2025-02-18 180651.png"));
    Icon arti_Beyaz = new ImageIcon(getClass().getResource("/Ýconlar/Ekran görüntüsü 2025-02-18 181648.png"));
    Icon eksi_Siyah = new ImageIcon(getClass().getResource("/Ýconlar/Eksi_Siyah.png"));
    Icon eksi_Beyaz = new ImageIcon(getClass().getResource("/Ýconlar/Eksi_Beyaz.png"));
    Icon hedef_Siyah2 = new ImageIcon(getClass().getResource("/Ýconlar/Hedef_Siyah2.png"));
    Icon hedef_Beyaz = new ImageIcon(getClass().getResource("/Ýconlar/Hedef_Beyaz.png"));
    
    /**
     * Creates new form Zikirmatik
     */
    public Zikirmatik() {
        initComponents();
        lbl_Hedef.setVisible(false);
        lbl_Kalan.setVisible(false);
        txt_HedefAyarla.setVisible(false);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_AnaPanel = new javax.swing.JPanel();
        btn_HedefAyarla = new javax.swing.JButton();
        lbl_ZikirSayisi = new javax.swing.JLabel();
        btn_Azalt = new javax.swing.JButton();
        btn_Arttir = new javax.swing.JButton();
        lbl_ArapcaBaslik = new javax.swing.JLabel();
        lbl_TurkceBaslik = new javax.swing.JLabel();
        btn_Sifirla = new javax.swing.JButton();
        lbl_Hedef = new javax.swing.JLabel();
        lbl_Kalan = new javax.swing.JLabel();
        txt_HedefAyarla = new javax.swing.JTextField();
        lbl_AnaResim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_AnaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_HedefAyarla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ýconlar/Hedef_Beyaz.png"))); // NOI18N
        btn_HedefAyarla.setText("Hedef ayarla");
        btn_HedefAyarla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HedefAyarlaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HedefAyarlaMouseExited(evt);
            }
        });
        btn_HedefAyarla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HedefAyarlaActionPerformed(evt);
            }
        });
        pnl_AnaPanel.add(btn_HedefAyarla, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 120, 100));

        lbl_ZikirSayisi.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ZikirSayisi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_ZikirSayisi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ZikirSayisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ZikirSayisi.setText("0");
        lbl_ZikirSayisi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Okunan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnl_AnaPanel.add(lbl_ZikirSayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, 50));

        btn_Azalt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ýconlar/Eksi_Beyaz.png"))); // NOI18N
        btn_Azalt.setText("Azalt");
        btn_Azalt.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_Azalt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AzaltMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AzaltMouseExited(evt);
            }
        });
        btn_Azalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AzaltActionPerformed(evt);
            }
        });
        pnl_AnaPanel.add(btn_Azalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 120, 100));

        btn_Arttir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Arttir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ýconlar/Ekran görüntüsü 2025-02-18 181648.png"))); // NOI18N
        btn_Arttir.setText("Arttýr");
        btn_Arttir.setBorder(null);
        btn_Arttir.setHideActionText(true);
        btn_Arttir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_Arttir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_Arttir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_Arttir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ArttirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ArttirMouseExited(evt);
            }
        });
        btn_Arttir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ArttirActionPerformed(evt);
            }
        });
        pnl_AnaPanel.add(btn_Arttir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, 110));

        lbl_ArapcaBaslik.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_ArapcaBaslik.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ArapcaBaslik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_ArapcaBaslik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ýconlar/Ekran görüntüsü 2025-02-17 164905.png"))); // NOI18N
        pnl_AnaPanel.add(lbl_ArapcaBaslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 510, 20));

        lbl_TurkceBaslik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_TurkceBaslik.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TurkceBaslik.setText("Allah'ým! Seni anýp zikretmek, nimetine þükretmek, sana lâyýk ibadet etmek için bana yardým eyle..'");
        pnl_AnaPanel.add(lbl_TurkceBaslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 20));

        btn_Sifirla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ýconlar/Restart.png"))); // NOI18N
        btn_Sifirla.setText("Sýfýrla");
        btn_Sifirla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SifirlaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SifirlaMouseExited(evt);
            }
        });
        btn_Sifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SifirlaActionPerformed(evt);
            }
        });
        pnl_AnaPanel.add(btn_Sifirla, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 110, 100));

        lbl_Hedef.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Hedef.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Hedef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Hedef.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Hedef", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnl_AnaPanel.add(lbl_Hedef, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, 20));

        lbl_Kalan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Kalan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Kalan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Kalan.setToolTipText("");
        lbl_Kalan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kalan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnl_AnaPanel.add(lbl_Kalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 120, 50));

        txt_HedefAyarla.setBackground(new java.awt.Color(0, 0, 0));
        txt_HedefAyarla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_HedefAyarla.setForeground(new java.awt.Color(255, 255, 255));
        txt_HedefAyarla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Hedefinizi giriniz:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 8), new java.awt.Color(255, 255, 255))); // NOI18N
        txt_HedefAyarla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_HedefAyarlaKeyReleased(evt);
            }
        });
        pnl_AnaPanel.add(txt_HedefAyarla, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, 40));

        lbl_AnaResim.setForeground(new java.awt.Color(204, 255, 204));
        lbl_AnaResim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_AnaResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quran-7622609_640.jpg"))); // NOI18N
        lbl_AnaResim.setLabelFor(lbl_AnaResim);
        lbl_AnaResim.setToolTipText("");
        lbl_AnaResim.setOpaque(true);
        pnl_AnaPanel.add(lbl_AnaResim, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Global deðiþkenler
    public int zikirSayisi=0;
    public int hedefZikir;
    public int kalan;
    public int sayac=0;
    
    private void btn_ArttirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ArttirActionPerformed
        // TODO add your handling code here:
        if(hedefZikir==0 && txt_HedefAyarla.isVisible()==true){
            JOptionPane.showMessageDialog(rootPane, "Hedefinizi giriniz.");
            return;
        }
        
        
        zikirSayisi++;
        lbl_ZikirSayisi.setText(String.valueOf(zikirSayisi)); 
        
        
        
        if(txt_HedefAyarla.isVisible()==true){
            sayac++;
            kalan=hedefZikir-sayac;
            lbl_Kalan.setText(String.valueOf(kalan));
            if(zikirSayisi==hedefZikir){
            JOptionPane.showMessageDialog(rootPane, "Hedefinize ulaþýldý!");
            lbl_ZikirSayisi.setText("");
            txt_HedefAyarla.setText("");
            lbl_Kalan.setText("");
            zikirSayisi=0;
            hedefZikir=0;
            sayac=0;
            kalan=0;
        }
        }
        
    }//GEN-LAST:event_btn_ArttirActionPerformed

    private void btn_AzaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AzaltActionPerformed
        // TODO add your handling code here:
        if(zikirSayisi-1==-1){
            JOptionPane.showMessageDialog(rootPane,"Okunan zikir sayýnýz negatif olamaz!", "Uyarý", JOptionPane.WARNING_MESSAGE); 
            return;
        }
         if(txt_HedefAyarla.isVisible()==true){
            sayac--;
            kalan=hedefZikir-sayac;
            lbl_Kalan.setText(String.valueOf(kalan));
         }
        zikirSayisi--;
        lbl_ZikirSayisi.setText(String.valueOf(zikirSayisi));
    }//GEN-LAST:event_btn_AzaltActionPerformed

    private void btn_SifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SifirlaActionPerformed
        // TODO add your handling code here:
        if(zikirSayisi==0){
            JOptionPane.showMessageDialog(rootPane, "Zikir sayýnýz zaten sýfýrdýr!");
            lbl_Hedef.setVisible(false);
            lbl_Kalan.setVisible(false);
            txt_HedefAyarla.setVisible(false);
            
            
        }
        else{
            zikirSayisi=0;
            hedefZikir=0;
        lbl_ZikirSayisi.setText(String.valueOf(zikirSayisi));
        txt_HedefAyarla.setText("");
        lbl_Kalan.setText("");
        
            lbl_Hedef.setVisible(false);
            lbl_Kalan.setVisible(false);
            txt_HedefAyarla.setVisible(false);
        
        JOptionPane.showMessageDialog(rootPane, "Zikir sýfýrlandý!");
        }
        
    }//GEN-LAST:event_btn_SifirlaActionPerformed

    private void btn_HedefAyarlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HedefAyarlaActionPerformed
        // TODO add your handling code here:
        
        if(zikirSayisi!=0){
            int secim = JOptionPane.showConfirmDialog(null, "Zikir sayýnýz sýfýrlanacaktýr.\nDevam etmek istiyor musunuz?", "Onay", JOptionPane.YES_NO_OPTION);
           
            if (secim == JOptionPane.YES_OPTION) {
            lbl_Hedef.setVisible(true);
            lbl_Kalan.setVisible(true);
            txt_HedefAyarla.setVisible(true);
            zikirSayisi=0;
            lbl_ZikirSayisi.setText(String.valueOf(zikirSayisi));
        } 
            else{
                lbl_Hedef.setVisible(false);
            lbl_Kalan.setVisible(false);
            txt_HedefAyarla.setVisible(false);
            }
               }
        else{
            lbl_Hedef.setVisible(true);
            lbl_Kalan.setVisible(true);
            txt_HedefAyarla.setVisible(true);
        }
        
        
        
        
    }//GEN-LAST:event_btn_HedefAyarlaActionPerformed

    private void txt_HedefAyarlaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HedefAyarlaKeyReleased
        // TODO add your handling code here:
         try {
        hedefZikir = Integer.valueOf(txt_HedefAyarla.getText());
        lbl_Kalan.setText(String.valueOf(hedefZikir));
    } catch (NumberFormatException e) {
        // Eðer sayý deðilse hata almamak için boþ geçiyoruz
    }
    }//GEN-LAST:event_txt_HedefAyarlaKeyReleased

    private void btn_ArttirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ArttirMouseEntered
        btn_Arttir.setIcon(arti_Siyah);
    }//GEN-LAST:event_btn_ArttirMouseEntered

    private void btn_ArttirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ArttirMouseExited
        btn_Arttir.setIcon(arti_Beyaz);
    }//GEN-LAST:event_btn_ArttirMouseExited

    private void btn_SifirlaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SifirlaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SifirlaMouseEntered

    private void btn_SifirlaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SifirlaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SifirlaMouseExited

    private void btn_AzaltMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AzaltMouseEntered
        // TODO add your handling code here:
        btn_Azalt.setIcon(eksi_Siyah);
    }//GEN-LAST:event_btn_AzaltMouseEntered

    private void btn_AzaltMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AzaltMouseExited
        // TODO add your handling code here:
        btn_Azalt.setIcon(eksi_Beyaz);
    }//GEN-LAST:event_btn_AzaltMouseExited

    private void btn_HedefAyarlaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HedefAyarlaMouseEntered
        // TODO add your handling code here:
        btn_HedefAyarla.setIcon(hedef_Siyah2);
    }//GEN-LAST:event_btn_HedefAyarlaMouseEntered

    private void btn_HedefAyarlaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HedefAyarlaMouseExited
        // TODO add your handling code here:
        btn_HedefAyarla.setIcon(hedef_Beyaz);
    }//GEN-LAST:event_btn_HedefAyarlaMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Zikirmatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Zikirmatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Zikirmatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Zikirmatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Zikirmatik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Arttir;
    private javax.swing.JButton btn_Azalt;
    private javax.swing.JButton btn_HedefAyarla;
    private javax.swing.JButton btn_Sifirla;
    private javax.swing.JLabel lbl_AnaResim;
    private javax.swing.JLabel lbl_ArapcaBaslik;
    private javax.swing.JLabel lbl_Hedef;
    private javax.swing.JLabel lbl_Kalan;
    private javax.swing.JLabel lbl_TurkceBaslik;
    private javax.swing.JLabel lbl_ZikirSayisi;
    private javax.swing.JPanel pnl_AnaPanel;
    private javax.swing.JTextField txt_HedefAyarla;
    // End of variables declaration//GEN-END:variables
}
